version: 2

sources:
  - name: raw
    database: dbtdb 
    schema: dbt_raw_data 
    tables:
      - name: Transactions
        describe: Transactions information
     

models:
  - name: bigCustomerTransactions
    description: Deposit transactions with value of over 7,000,000

  - name: suspectTransactions
    description: Withdrawal transactions with value of over 5,000,000. Bank policy expects 4,999,000 and below per transaction

